server:
  port: 8761
spring:
  application:
    name: registry
eureka:
  instance:
    prefer-ip-address: true
  client:
    should-unregister-on-shutdown: true
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false