spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/shared
  security:
    user:
      name: configclient
      password: configpassword
server:
  port: 8888